# Generated by Django 3.0.6 on 2020-05-31 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import responses.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question01', models.CharField(default='Not Answered', max_length=2500)),
                ('question02', models.CharField(default='Not Answered', max_length=2500)),
                ('question03', models.CharField(default='Not Answered', max_length=2500)),
                ('question04', models.CharField(default='Not Answered', max_length=2500)),
                ('question05', models.CharField(default='Not Answered', max_length=2500)),
                ('question06', models.CharField(default='Not Answered', max_length=2500)),
                ('file', models.FileField(blank=True, max_length=254, null=True, upload_to=responses.models.generate_filename)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
