# Generated by Django 3.0.7 on 2020-06-07 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('responses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responses',
            name='photo_upload',
        ),
        migrations.AlterField(
            model_name='responses',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
