# Generated by Django 3.0.6 on 2020-05-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='question02',
            field=models.CharField(default='Not Answered', max_length=2500),
        ),
        migrations.AddField(
            model_name='responses',
            name='question03',
            field=models.CharField(default='Not Answered', max_length=2500),
        ),
        migrations.AddField(
            model_name='responses',
            name='question04',
            field=models.CharField(default='Not Answered', max_length=2500),
        ),
        migrations.AddField(
            model_name='responses',
            name='question05',
            field=models.CharField(default='Not Answered', max_length=2500),
        ),
        migrations.AddField(
            model_name='responses',
            name='question06',
            field=models.CharField(default='Not Answered', max_length=2500),
        ),
    ]
