# Generated by Django 3.0.6 on 2020-06-02 23:17

from django.db import migrations
import private_storage.fields
import private_storage.storage.files
import responses.models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='file_upload',
            field=private_storage.fields.PrivateFileField(blank=True, max_length=254, null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to=responses.models.generate_filename),
        ),
    ]
