# Generated by Django 3.0.6 on 2020-06-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='question01',
            field=models.CharField(blank=True, default='', max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='responses',
            name='question02',
            field=models.CharField(blank=True, default='', max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='responses',
            name='question03',
            field=models.CharField(blank=True, default='', max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='responses',
            name='question04',
            field=models.CharField(blank=True, default='', max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='responses',
            name='question05',
            field=models.CharField(blank=True, default='', max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='responses',
            name='question06',
            field=models.CharField(blank=True, default='', max_length=2500, null=True),
        ),
    ]
