# Generated by Django 3.0.8 on 2020-07-06 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0002_auto_20200607_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='question01',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='responses',
            name='question02',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='responses',
            name='question03',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='responses',
            name='question04',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='responses',
            name='question05',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='responses',
            name='question06',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
    ]
