# Generated by Django 3.0.6 on 2020-06-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0002_auto_20200603_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='file_location',
            field=models.CharField(blank=True, default='', max_length=254, null=True),
        ),
    ]
