# Generated by Django 3.0.8 on 2020-07-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0004_auto_20200706_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='status',
            field=models.CharField(choices=[('Not Submitted', 'Not Submitted'), ('Submitted', 'Submitted'), ('Written', 'Written'), ('Uploaded', 'Uploaded')], default='Submitted', max_length=20),
        ),
    ]
