# Generated by Django 3.0.8 on 2020-08-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0005_auto_20200713_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='status',
            field=models.CharField(choices=[('Not Submitted', 'Not Submitted'), ('Submitted', 'Submitted'), ('Written', 'Written'), ('Uploaded', 'Uploaded'), ('CommonApp', 'CommonApp')], default='Submitted', max_length=20),
        ),
    ]
